---
- name: Create firewall
  uri:
    url: "{{ hetzner_firewall_webservice_base_url }}/firewall"
    method: POST
    user: "{{ hetzner_firewall_webservice_username }}"
    password: "{{ hetzner_firewall_webservice_password }}"
    status_code: 201
    body:
      server_ip: 123.123.123.123
      whitelist_hos: true
      status: active
      rules:
        input:
          - action: accept
            ip_version: ipv4
            name: Allow all
    force_basic_auth: yes
    body_format: json
