---
- name: Prepare Hetzner Robot Mock API for *_template scenario
  hosts: localhost
  tasks:
    - name: Include start Hetzner Robot Mock API
      include: ./start_hetzner_robot_mock_api.yml
    - name: Include create template
      include: ./create_template.yml

- name: Prepare controller
  hosts: localhost
  tasks:
    - name: Prepare controller
      include: controller.yml
