---
language: python
services: docker

env:
  global:
    - PROJECT_DIR: $TRAVIS_BUILD_DIR
    - ROLE_NAME: hetzner_firewall

before_script:
  - wget https://raw.githubusercontent.com/nl2go/docker-molecule/1.0.1/docker-compose.yml

script:
  - docker-compose run molecule molecule test --all

after_script:
  - docker-compose down

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
