---
- name: Get list of existing firewall templates
  local_action:
    module: uri
    url: "https://robot-ws.your-server.de/firewall/template"
    method: GET
    user: "{{ hetzner_firewall_webservice_username }}"
    password: "{{ hetzner_firewall_webservice_password }}"
    status_code:
      - 200
      - 404
  register: get_templates_response

- set_fact:
    origin_template_references: "{{ get_templates_response.json |  selectattr('firewall_template', 'defined') | map(attribute='firewall_template') | list }}"

- debug:
    msg: "{{ origin_template_references }}"

- local_action:
    module: uri
    url: "https://robot-ws.your-server.de/firewall/template/{{ item['id'] }}"
    method: GET
    user: "{{ hetzner_firewall_webservice_username }}"
    password: "{{ hetzner_firewall_webservice_password }}"
    status_code:
      - 200
  register: get_template_response
  with_items: "{{ origin_template_references }}"

- set_fact:
    origin_templates: "{{ get_template_response['results'] | map(attribute='json') | map(attribute='firewall_template') | list }}"

- debug:
    msg: "{{ origin_templates }}"

- set_fact:
    change_set_templates: "{{ hetzner_firewall_templates | hetzner_firewall_template_defaults | hetzner_firewall_change_set(origin_templates) }}"

- debug:
    msg: "{{ change_set_templates }}"

- name: Create templates
  local_action:
    module: uri
    url: "https://robot-ws.your-server.de/firewall/template"
    method: POST
    user: "{{ hetzner_firewall_webservice_username }}"
    password: "{{ hetzner_firewall_webservice_password }}"
    status_code: 201
    body: "{{ item }}"
    body_format: form-urlencoded
    changed_when: yes
  with_items: "{{ change_set_templates['create'] }}"

- name: Update templates
  local_action:
    module: uri
    url: "https://robot-ws.your-server.de/firewall/template/{{ item['id'] }}"
    method: POST
    user: "{{ hetzner_firewall_webservice_username }}"
    password: "{{ hetzner_firewall_webservice_password }}"
    status_code: 200
    body: "{{ item }}"
    body_format: form-urlencoded
    changed_when: yes
  with_items: "{{ change_set_templates['update'] }}"

- name: Delete templates
  local_action:
    module: uri
    url: "https://robot-ws.your-server.de/firewall/template/{{ item['id'] }}"
    method: DELETE
    user: "{{ hetzner_firewall_webservice_username }}"
    password: "{{ hetzner_firewall_webservice_password }}"
    status_code: 200
    changed_when: yes
  with_items: "{{ change_set_templates['delete'] }}"
