---
- name: Create firewall templates
  local_action:
    module: uri
    url: "https://robot-ws.your-server.de/firewall/template"
    method: POST
    headers:
      Content-Type: application/x-www-form-urlencoded
    user: "{{ hetzner_firewall_webservice_username }}"
    password: "{{ hetzner_firewall_webservice_password }}"
    status_code: 201
    body: "{{ item | hetzner_firewall_form_urlencode }}"
    body_format: raw
    changed_when: yes
  with_items: "{{ change_set_templates['create'] }}"

- name: Update firewall templates
  local_action:
    module: uri
    url: "https://robot-ws.your-server.de/firewall/template/{{ item['id'] }}"
    method: POST
    headers:
      Content-Type: application/x-www-form-urlencoded
    user: "{{ hetzner_firewall_webservice_username }}"
    password: "{{ hetzner_firewall_webservice_password }}"
    status_code: 200
    body: "{{ item | hetzner_firewall_form_urlencode }}"
    body_format: raw
    changed_when: yes
  with_items: "{{ change_set_templates['update'] }}"

- name: Delete firewall templates
  local_action:
    module: uri
    url: "https://robot-ws.your-server.de/firewall/template/{{ item['id'] }}"
    method: DELETE
    user: "{{ hetzner_firewall_webservice_username }}"
    password: "{{ hetzner_firewall_webservice_password }}"
    status_code: 200
    changed_when: yes
  with_items: "{{ change_set_templates['delete'] }}"
