---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: instance
    image: centos:7
    dockerfile: ../resources/playbooks/Dockerfile.j2
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    prepare: ../resources/playbooks/prepare.yml
    converge: ../resources/playbooks/playbook.yml
    cleanup: ../resources/playbooks/cleanup.yml
verifier:
  name: testinfra
  env:
    HETZNER_ROBOT_BASE_URL: http://hetzner-robot:3000
  lint:
    name: flake8
