---
- name: Map firewall template name and host IP
  set_fact:
    firewall_template_name: "{{ ( hostvars[hostname].hetzner_firewall_template | default({}) ).name | default(None) }}"
    host_ip: "{{ hostvars[hostname].ansible_host }}"

- name: Map firewall template with rules using previously defined template name
  set_fact:
    firewall_template: "{{ hetzner_firewall_templates | selectattr('name', 'equalto', firewall_template_name) | hetzner_firewall_template_defaults | first }}"
  when: firewall_template_name | length > 0
