---
- name: "Get firewall template for {{ hostname }}"
  include_tasks: read.yml
- name: "Update firewall configuration for {{ hostname }}"
  include_tasks: update.yml
  when: hostvars[hostname].hetzner_firewall_host is defined
